version: 0.2


phases:
  install:
    commands:
      - echo install serverless framework test pipeline
      - npm install -g serverless
  pre_build:
    commands:
      - echo install pre build commands
  build:
    commands:
      - echo deployment started `date`
      - echo deploy serverless framework custom codebase
      - sls deploy -v
  post_build:
    commands:
      - echo post build completed on `date`

